#!/bin/bash

where="$HOME/Media/Tree/database"
output="$where/tree.csv"

time find $HOME/Media -type f -exec sh -c 'stats=$(stat -c "%.19y\t%.19w\t%.19z" "{}"); echo -e "$stats\t$(cksum "{}" | cut -d " " -f 1 | cut -b1-9)\t$(stat -c "%s\t%n" "{}")"' \; > $output

sed -i 's#/home/clyde/Media#..#g' $output


cd $where
test -e .git || git init
git add tree.csv
git commit -m "automatic commit"
